version: 2

models:
    - name: stg_dimproductcategory
      columns:
       - name: productcategorykey
         description: ' ' 
       - name: productcategoryalternatekey
         description: ' ' 
       - name: englishproductcategoryname
         description: ' ' 
       - name: spanishproductcategoryname
         description: ' ' 
       - name: frenchproductcategoryname
         description: ' ' 
           
